room1_coordx: -6.13
room1_coordy: 8.2
room2_coordx: -5.97
room2_coordy: -8.21
hall_coordx: 0.0
hall_coordy: 0.0
office1_coordx: -5.37
office1_coordy: 1.13
office2_coordx: -5.22
office2_coordy: -1.37
storage1_coordx: 12.5
storage1_coordy: 7.89
storage2_coordsx: 12.47
storage2_coordsy: -7.72